services:
  docker-rsync-ofelia:
    restart: always
    build:
      context: .
    volumes:
      - "./ofelia_config.ini:/ofelia_config.ini"
      - "./known_hosts:/known_hosts"
      # Uncomment if you'd like to run a custom script
      #- "./script.sh:/script.sh"
